### PR TITLE
Declare package license and include license and notice

### PR DESCRIPTION
**Pull request by bingenito**
For the nuget client package, declare the license and embed the license and notice for downstream consumers.  Exposing the license helps facilitate more automated onboarding for some enterprise setups.

---
THIS SOFTWARE IS CONTRIBUTED SUBJECT TO THE TERMS OF THE FINOS CORPORATE CONTRIBUTOR LICENSE AGREEMENT.
 
THIS SOFTWARE IS LICENSED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE AND ANY WARRANTY OF NON-INFRINGEMENT, ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE. THIS SOFTWARE MAY BE REDISTRIBUTED TO OTHERS ONLY BY EFFECTIVELY USING THIS OR ANOTHER EQUIVALENT DISCLAIMER IN ADDITION TO ANY OTHER REQUIRED LICENSE TERMS.

### CODE REVIEW

**Review by Vivek-NatWest — APPROVED** [review]

**Comment by kriswest** [comment]
@Vivek-NatWest could you push the version with this merged to nuget? @bingenito is still stuck until its published.

**Comment by Vivek-NatWest** [comment]
> @Vivek-NatWest could you push the version with this merged to nuget? @bingenito is still stuck until its published.
Unfortunately, the automated semantic-release did not trigger the publishing of new version as it works on commit message, _'[2:49:06 PM] [semantic-release] › ℹ  There are no relevant changes, so no new version is released.'_ 
I have raised a pull req, which is awaiting approval from @manish-nwm, (Diwali holidays here :) )  which would publish the NuGet package. Hopefully tomorrow,  new version would be released. 

We need more reviewers to speed up, where you able to add yourself as reviewer @kriswest?

**Comment by kriswest** [comment]
To the project? No, I can't add myself. You may have the rights to add me if there is a github team (I seem to have that right on the FDC3 project, but didn't always).

Either @robmoffat maybe able to do it, otherwise we may need the help of @maoo or @TheJuanAndOnly99 - failing that an email to help@finos.org.

**Comment by Vivek-NatWest** [comment]
> To the project? No, I can't add myself. You may have the rights to add me if there is a github team (I seem to have that right on the FDC3 project, but didn't always).
> 
> Either @robmoffat maybe able to do it, otherwise we may need the help of @maoo or @TheJuanAndOnly99 - failing that an email to [help@finos.org](mailto:help@finos.org).

It seems, I don't have rights, cant see you in reviewers list. I had elevated access for sometime few months back but its gone now. Sure let me drop a mail to Juan/FINOS for help here.

**Pull request merged**
