### PR TITLE
.net projects release setup

### PR DESCRIPTION
**Pull request by Vivek-NatWest**

### CODE REVIEW

**Comment by Vivek-NatWest** [comment]
@maoo : For nuget package release, NUGET_TOKEN is required to publish to https://www.nuget.org/.

**Comment by maoo** [comment]
> @maoo : For nuget package release, NUGET_TOKEN is required to publish to https://www.nuget.org/.

Added the secret. When published, your package will show on https://www.nuget.org/profiles/finos

**Comment by Vivek-NatWest** [comment]
> > @maoo : For nuget package release, NUGET_TOKEN is required to publish to https://www.nuget.org/.
> 
> Added the secret. When published, your package will show on https://www.nuget.org/profiles/finos



> > @maoo : For nuget package release, NUGET_TOKEN is required to publish to https://www.nuget.org/.
> 
> Added the secret. When published, your package will show on https://www.nuget.org/profiles/finos

Thanks @maoo. I tried publish initial package but got error: Pushing Finos.Fdc3.Backplane.Client.1.0.0-alpha.1.nupkg to 'https://www.nuget.org/api/v2/package'...
  PUT https://www.nuget.org/api/v2/package/
  Forbidden https://www.nuget.org/api/v2/package/ 540ms
error: Response status code does not indicate success: 403 (The specified API key is invalid, has expired, or does not have permission to access the specified package.).

Is there any pattern applied in profile 'finos' for allowed packages?

**Review by manish-nwm — APPROVED** [review]

**Pull request merged**
