### PR TITLE
Feature/merge alpha to beta

### PR DESCRIPTION
**Pull request by Vivek-NatWest**

### CODE REVIEW

**Review by kriswest — COMMENTED** [review]
@Vivek-NatWest I'm not seeing changes from https://github.com/finos/backplane/pull/50/files in this PR - is that expected?

Also, I note the version number being merged is 1.0.0-alpha.4, should that be updated in the feature branch?

Is there documentation of how you use the alpha/beta/main branches in the project somewhere that I should review?

**Review by manish-nwm — APPROVED** [review]

**Comment by Vivek-NatWest** [comment]
> @Vivek-NatWest I'm not seeing changes from https://github.com/finos/backplane/pull/50/files in this PR - is that expected?
> 
> Also, I note the version number being merged is 1.0.0-alpha.4, should that be updated in the feature branch?
> 
> Is there documentation of how you use the alpha/beta/main branches in the project somewhere that I should review?



> @Vivek-NatWest I'm not seeing changes from https://github.com/finos/backplane/pull/50/files in this PR - is that expected?
> 
> Also, I note the version number being merged is 1.0.0-alpha.4, should that be updated in the feature branch?
> 
> Is there documentation of how you use the alpha/beta/main branches in the project somewhere that I should review?

Sorry missed this comment before merging. This PR is to promote alpha to beta, post which to promote to main to release the new version which would contain the https://github.com/finos/backplane/pull/50/files as it is already merged to main.

Correctly pointed out that the feature branch need not have version info which got into it during merging, my bad. Although that version is auto-replaced by the release version by the ci pipeline, it should be auto-corrected with the automated release workflow.

In terms of branching strategy, it is based on release streams:
Alpha (1.0.0-alpha.X) : Feature development 
Beta(1.0.0-beta.X): Release candidate
Main (1.0.0)- Stable.
Repo doesn't have documentation yet for this. Definitely something to raise an issue for and work to add. Let me know, I will raise an issue and would appreciate any suggestions and improvements in any scope.

**Pull request merged**
